### PR TITLE
[RF][Main][Footer Website][Cookies panel] testBelowButtonsAndTextIntoCookiePanel()<Kater1naG>

### PR DESCRIPTION
**Pull request by Kater1naG**
changes added

[RF] - https://trello.com/c/JvfEjQcz/796-rfmainfooter-websitecookies-panel-testbelowbuttonsandtextintocookiepanelkater1nag

### CODE REVIEW

**Comment by NataliiaOliver** [comment]
Attach please PR link to AT card

**Review by NataliiaOliver — APPROVED** [review]
LGTM

**Comment by Kater1naG** [comment]
> 

I don't need AT card, it's a Refactoring

**Comment by NataliiaOliver** [comment]
Sorry, I meant RF card, I mixed it up :)

**Review by AnnaGlumova — APPROVED** [review]

**Comment by larisabratukhina** [comment]
сорри, а где у вас строка String expectedButtons?, не вижу в тесте

**Pull request merged**
