### PR TITLE
[RF][Start][Menu][API] All tests deleted <RadasIvan>

### PR DESCRIPTION
**Pull request by RadasIvan**
testH2TagText_WhenSearchingCityCountry() deleted

testTitleOfPage() deleted.

[RF] - https://trello.com/c/SYc7fCh3
[RF] - https://trello.com/c/qAlqWX0s

### CODE REVIEW

**Comment by RadasIvan** [comment]
[[RF][Start][Weather][Current Weather][h2] testH2TagText_WhenSearchingCityCountry() deleted <RadasIvan>](https://trello.com/c/SYc7fCh3/294-rfstartweathercurrent-weatherh2-testh2tagtextwhensearchingcitycountry-deleted-radasivan)

**Comment by RadasIvan** [comment]
[[RF][Start][Menu][API] testTitleOfPage() deleted <RadasIvan>](https://trello.com/c/qAlqWX0s/296-rfstartmenuapi-testtitleofpage-deleted-radasivan)

**Review by ArinaJur — CHANGES_REQUESTED** [review]
Пожалуйста поменяйте название PR на 
[RF][Start][Menu][API] All tests deleted <RadasIvan>

**Review by gdikhsanov — APPROVED** [review]

**Comment by gdikhsanov** [comment]
Да, название PR поменяйте - пропустил этот момент.

**Review by ElNov686 — APPROVED** [review]

**Review by ArinaJur — APPROVED** [review]

**Pull request merged**
